# Generated by Django 3.1.7 on 2021-05-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='email address'), max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='surname',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='email address'), max_length=500),
        ),
    ]
