# Generated by Django 3.1.7 on 2021-05-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210506_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='surname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
